@echo off
setlocal EnableDelayedExpansion

title NexStep — Build Standalone Android APK

echo ============================================================
echo   NexStep AI — Build Standalone Android APK (Physical Device)
echo ============================================================
echo.

set "ROOT=%~dp0"
if "%ROOT:~-1%"=="\" set "ROOT=%ROOT:~0,-1%"
set "MOBILE_DIR=%ROOT%\mobile"
set "APK_OUT=%ROOT%\apks"
set "OUT_APK=%APK_OUT%\NexStep.apk"

:: ── Detect LAN IP (Wi-Fi preferred) ─────────────────────────────────
set "LAN_IP="
for /f "tokens=4" %%a in ('route print ^| findstr 0.0.0.0 ^| findstr /v "0.0.0.0.*0.0.0.0"') do (
    if not defined LAN_IP (
        set "LAN_IP=%%a"
    )
)
if not defined LAN_IP (
    set "LAN_IP=192.168.100.13"
    echo [WARN] Could not detect LAN IP, falling back to !LAN_IP!
)

echo [OK] Detected Host Machine LAN IP: !LAN_IP!
echo [INFO] Setting EXPO_PUBLIC_API_URL=http://!LAN_IP!:3001
echo.

:: ── Recreate mobile/.env with current LAN IP ─────────────────────────
(
  echo # NexStep Mobile — Auto-generated by BUILD_APK.bat
  echo # Backend must run on this PC, reachable via Wi-Fi on port 3001
  echo EXPO_PUBLIC_API_URL=http://!LAN_IP!:3001
  echo EXPO_PUBLIC_ENV=development
) > "%MOBILE_DIR%\.env"

echo [OK] Updated %MOBILE_DIR%\.env with new backend URL
echo.

:: ── Ensure output dir exists ─────────────────────────────────────────
if not exist "%APK_OUT%" (
    mkdir "%APK_OUT%" >nul 2>&1
    echo [OK] Created output directory: %APK_OUT%
)

:: ── Build via local Gradle (no Expo cloud login required) ────────────
echo ============================================================
echo   Building Debug Android APK via local Gradle...
echo   (This can take 3-8 minutes the first time.)
echo ============================================================
echo.

cd /d "%MOBILE_DIR%\android"

set "JAVA_HOME=C:\jdk-23.0.1"
set "ANDROID_HOME=C:\Users\abdur\AppData\Local\Android\Sdk"
set "ANDROID_SDK_ROOT=C:\Users\abdur\AppData\Local\Android\Sdk"
set "PATH=%JAVA_HOME%\bin;%ANDROID_HOME%\platform-tools;%PATH%"

echo [INFO] JAVA_HOME=%JAVA_HOME%
echo [INFO] ANDROID_HOME=%ANDROID_HOME%
echo [INFO] API URL baked into APK = http://!LAN_IP!:3001
echo.
echo [INFO] Running: gradlew.bat assembleDebug --no-daemon
echo.

call gradlew.bat assembleDebug --no-daemon
set "BUILD_RC=%ERRORLEVEL%"

if "%BUILD_RC%" neq "0" (
    echo.
    echo [ERROR] Gradle build failed with exit code %BUILD_RC%.
    echo         Scroll up to see the Android Gradle error message.
    echo.
    echo Common fixes:
    echo   - Open Android Studio once and let it download missing SDK components
    echo   - Run: cd mobile ^&^& npx expo prebuild --clean
    echo         then re-run BUILD_APK.bat
    echo.
    pause
    exit /b 1
)

echo.
echo [OK] Gradle assembleDebug completed.

:: ── Locate and copy the APK ──────────────────────────────────────────
set "BUILT_APK="
for /f "delims=" %%f in ('dir /b /s /a-d "%MOBILE_DIR%\android\app\build\outputs\apk\debug\*.apk" 2^>nul') do (
    if not defined BUILT_APK set "BUILT_APK=%%f"
)

if not defined BUILT_APK (
    echo [ERROR] Built APK not found under android\app\build\outputs\apk\debug\
    echo         Check Gradle output above for warnings.
    pause
    exit /b 1
)

echo [OK] Found built APK: !BUILT_APK!
copy /y "!BUILT_APK!" "%OUT_APK%" >nul
if %ERRORLEVEL% neq 0 (
    echo [ERROR] Failed to copy APK to %OUT_APK%
    pause
    exit /b 1
)

:: ── Print APK size ───────────────────────────────────────────────────
for %%A in ("%OUT_APK%") do set "APK_SIZE=%%~zA"
set /a APK_MB=APK_SIZE / 1048576

echo.
echo ============================================================
echo   APK BUILD SUCCESS!
echo ============================================================
echo.
echo   Output:   %OUT_APK%
echo   Size:     ~!APK_MB! MB
echo   Built at: %DATE% %TIME%
echo.
echo   Backend API URL (baked into this APK):
echo     http://!LAN_IP!:3001
echo.
echo   IMPORTANT — Before running on your phone:
echo   1. Start NexStep backend: double-click START_NEXSTEP.bat
echo      (Backend MUST run on this machine on port 3001)
echo   2. Connect your Android phone to the SAME Wi-Fi network
echo      as this PC (the Wi-Fi with IP !LAN_IP!).
echo   3. Copy the APK to your phone via USB / download / share:
echo      %OUT_APK%
echo   4. On your phone, tap the APK file in your file manager.
echo      Enable "Install from unknown sources" when prompted.
echo   5. Log in with the same account as the web app.
echo.
echo   ALTERNATIVE — Install over USB directly:
echo      Enable USB Debugging on your phone, plug in USB cable, then:
echo      adb install -r "%OUT_APK%"
echo.
echo   Opening output folder...
echo ============================================================
echo.

explorer "%APK_OUT%"
pause
exit /b 0
